[env:disco_l475vg_iot01a]
platform = ststm32
board = disco_l475vg_iot01a
framework = stm32cube
build_flags =
  -I"${platformio.packages_dir}/framework-stm32cubel4/Drivers/BSP/B-L475E-IOT01"
  -I"${platformio.packages_dir}/framework-stm32cubel4/Drivers/BSP/Components/lsm6dsl"
lib_ignore = lsm6dsl

; Flash via the on-board ST-LINK
upload_protocol = stlink
debug_tool = stlink


; Serial monitor (ST-LINK VCP) 
monitor_speed = 115200
monitor_eol = LF

monitor_port = COM5

; Useful monitor filters 
; - time: adds timestamps
; - printable: strips weird control chars
monitor_filters = log2file

; ===== Optional: build extras =====
; build_type = debug
; build_flags =
;   -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
